export default {
  back: require('../images/ic_back_white.png'),
  placeholder: require('../images/placeholder_image.png'),
  logo_login: require('../images/ic_logo_login.png'),
  ic_home_bottom: require('../images/ic_home_bottom.png'),
  ic_calendar_bottom: require('../images/ic_calender_bottom.png'),
  ic_file_bottom: require('../images/ic_file_bottom.png'),
  ic_setting_bottom: require('../images/ic_setting_bottom.png'),
  ic_weather: require('../images/ic_weather.png'),
  ic_success: require('../images/ic_success.png'),
  ic_error: require('../images/ic_failed.png'),
  ic_warning: require('../images/ic_warning.png'),
  ic_pagination_left: require('../images/ic_pagination_left.png'),
  ic_pagination_left_ipad: require('../images/ic_pagination_left_ipad.png'),
  ic_pagination_right: require('../images/ic_pagination_right.png'),
  ic_pagination_right_ipad: require('../images/ic_pagination_right_ipad.png'),
  ic_loading: require('../images/ic_loading.gif'),
  ic_checkbox: require('../images/ic_checkbox.png'),
};
